### ISSUE TITLE
[Bug]: Apiary generating infinite Netherite Bees

### ISSUE THREAD

**Issue by Urthelion** [Resourceful-Bees/ResourcefulBees#314] opened 2021-12-08 06:48 UTC
### Bug Description

Bees working normally and magically appearing new netherite bees

### How to Reproduce?

Not sure if this is actually producing the bug, but I had a Ghast Bee and a Diamond bee in the same Tier 3 Appiary. I noticed the Diamond bee disappeared so I'm guessing the Ghast mutated it and started the bug. 

I removed the appiary multiple times without a diamond bee and the bug persisted. Changing the Appiary block from that same place fixed it. Also I didn't add a Diamond Bee there again

I'm playing in Enigmatica 6 0.5.20

### Expected Behavior

Netherite is cool but that's too many bees :(

### Version

0.9.9.8

### Mod Loader Version

1.16.5 36.2.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment] 2021-12-08 06:55
I have had at least 4 or 5 reports of this happening and I have yet to figure out what is causing it as I can't get reliable reproduction steps. if you can provide steps to reproduce the issue with 100% accuracy, I would be more than happy to look into it

**Comment by Urthelion** [comment] 2021-12-08 08:03
You're right, simply mutating the bee inside an apiary doesn't reproduce the bug and having a netherite bee inside the apiary just kept a bee flying without hive inside the multiblock. Just tried it in creative. I'll keep trying to reproduce the bug, tho

**Comment by Heroncustom** [comment] 2022-01-30 20:49
Iv been having this issue as well

T1 apiary
1 netherrite bee
1 wither bee
1 withered bee

randomly a netherite bee appears and sometimes the withered bee mutates

has happned many times

also in another t1 apiary i have 
1 lapis 
1 glowing
1skeleton
1stoned
1mason

skeley and stone bees keep duplicating new ones and the glowing bees turns skely......

**Comment by Heroncustom** [comment] 2022-02-01 15:34
![2022-01-31_09 21 05](https://user-images.githubusercontent.com/98713243/151998754-f0057c0b-01c4-4289-986e-0865be588062.png)



i think i found my personal problem.......apiary was outside the chunk the build was in. once i moved it forward one block no more duping


check your chunk borders. (F3+G}

**Comment by Epic428** [comment] 2022-02-01 16:53
Strange that chunkborders would have any effect on a mutation which is unrelated to block entity ticking.

**Comment by Cloudy-Q** [comment] 2022-04-12 15:09
Hello, im also having this problem as well, im a littler versed in craft-tweaker scripts and noticing this happens on the Enigmatica 6 Expert pack. I have a video showing off the problem, but right now im trying to figure out if its a pack or mod issue, but im assuming mod, since it seems as if the problems been around for a bit. maybe a coding issue with the way the bees are replaced, instead of only summoning in 1 bee, it does a multiple or percent of (x) along with making the bee "special" in the sense as when it pollinates, it keeps its tag to replace the diamond bee without doing a check for nearby entity, but i will inform and update anything regarding if its the packs problem or not :) https://youtu.be/yq3VSlu-4u0

**Comment by Cloudy-Q** [comment] 2022-04-12 18:09
Okay so the problem seems to be with the way Enigmatica implemented their Ghast bees. The config file adds in a mutation for the Netherite bee with a "weight" of 10, thus multiplying the amount of bees you get with the mutation. This should be brought up with the E6 Devs as its all config based. I've made a report on their GitHub just now :)
![Screenshot 2022-04-12 103129](https://user-images.githubusercontent.com/103519242/163026478-8b554622-81b1-45da-b683-256fdaadc482.png)

**Comment by Epic428** [comment] 2022-04-13 04:09
FYI weight of 10 does not mean that you get 10 bees. It’s the weight distribution for all possible bees that can be created when ghast bee mutates a diamond bee.

 I.E. if it could create 10 different possible bees then the weight for the diamond bee selection would be 10/XX where XX is the sum of all bees the ghast could mutate the diamond bee into. If XX=50 then diamond bee would have a 20% chance of being picked out of the ten possible choices. if diamond bee is the only possible option then weighting has no effect as the result would always be a 100% chance.

**Comment by Cloudy-Q** [comment] 2022-04-13 04:59
> 

I learned that right now after mentioning this to the E6 devs! thank you for a more descriptive look into how it works, I learn something more and more each day, so I appreciate it :) 
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4631
Link to the Post I made, figured out it was a mod issue and is now being further looked into from what im seeing :)
https://github.com/Resourceful-Bees/ResourcefulBees/issues/333
Link to the newest post related to the post I made at E6 GitHub

**Comment by ThatGravyBoat** [comment] 2022-04-23 23:01
Ok so I think ive fixed this bug in the latest release, if any of you still run into the problem let me know but from my understanding, this has been fixed. If it still happens let me know and ill reopen the issue but for now I will close it.

**Closed as completed by ThatGravyBoat** 2022-04-23 23:01 UTC
Labels: bug, Can’t Reproduce
