### ISSUE TITLE
[Bug]: Diddybee one shotting & indestructible?

### ISSUE THREAD

**Issue by Xirita** [Resourceful-Bees/ResourcefulBees#356] opened 2022-09-15 08:59 UTC
### Bug Description

Hello :)

I keep getting one shot by the Diddybee in the "Other side" & it also can't be killed, can't even hit it with arrows so it is making areas of my game un-playable due to it being indestructible... is there a way to disable this bee or a fix or something?

Can't be good if it can't be killed & also one shots you (i had 120 armour & 27hearts for context)
I am using this mod as part of ATM 6 :)
Please help! 

### Version

1.16.5

### Mod Loader Version

1.16.5-0.10.6

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Felixargyl** [comment] 2022-09-15 10:15
its not a bug if you type in the JEI beediddy bee's it will say some sorta number with a e in it meaning itll be around the 2 billion damage, so its a normal bee

**Comment by ThatGravyBoat** [comment] 2022-10-31 12:31
Closing due to this being a a design choice by the pack developer who implemented the diddybee

**Closed as not planned by ThatGravyBoat** 2022-10-31 12:31 UTC
Labels: bug
