### ISSUE TITLE
[Bug]: Apiary spawns infinite netherite bees

### ISSUE THREAD

**Issue by BvLiemt** [Resourceful-Bees/ResourcefulBees#300] opened 2021-10-31 15:45 UTC
### Bug Description

![Infinity_bug_apiary](https://user-images.githubusercontent.com/64969677/139591061-1e8dcd3f-40af-4f70-bcb9-cd57b40b0188.png)

Somehow, my apiary keeps spawning infinite netherite bees. I added a netherite bee once, but removed it quickly after realising I had no wither roses (the flower for the bee in enigmatica 6, the modpack Im playing).  Ever since then, netherite bees have been 'magically' appearing in my apiary..... This is on a server running enigmatica 6, version 0.5.14 via curseforge.

There are no diamond bees in the apiary, so the transmutation is an unlikely source....

### How to Reproduce?

I haven't tested for reproduction yet, I may later.

### Expected Behavior

I expected it to _not produce infinite bees_

### Version

ResourcefulBees-1.16.5-0.9.9.6. is the file I found, more than that idk

### Mod Loader Version

forge-1.16.5-36.2.4

### Logs or additional context

As I said, this was in Enigmatica 6, and on a server. Sorry I cant give much more info than this, Im not exactly a programming savvy.

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment] 2021-10-31 15:47
Have you tried breaking and replacing the apiary?

**Comment by BvLiemt** [comment] 2021-11-11 20:57
Yea, this seems to work? For now at least.
As for potential causes, it _might_ have something to do with 'physically' removing a bee using a jar while within the apiary, but Im really not sure about that.

**Comment by Vaerys-Dawn** [comment] 2021-12-08 02:58
closing with cant reproduce

**Closed as completed by Vaerys-Dawn** 2021-12-08 02:58 UTC
Labels: bug, Can’t Reproduce
